### ISSUE TITLE
Problems with some receivers

### ISSUE THREAD

**Issue by royaldelux** [rooi/homebridge-lightwaverf#13]
First of all thanks for making the plugin for this device. I have a klikaanklikuit system with the ICU-1000 and it communicates perfect but there is still one problem. Only my dimmer switches will work, the normal on / off switch won't work. The home app on IOS10 says "unsuitable, This accessory is not supported by the app at this moment"  i have an old ICS-1000 with the LCD display (still works fine) home bridge gets the information directly from the host with my email added and the four digits password.

**Comment by rooi** [comment]
Hi,

I've glt the same setup as you, but without switches. From what I've heard, the lightwaverf switches do work, but I could not test it myself.

There are something you can try. The plugin uses the followibg package: https://github.com/rooi/node-lightwaverf/blob/master/index.js
Perhaps you can try if this works for you switches.

Otherwise please please post the content of your config.json and perhaps homebridge's console log. Note that they contain you login, so errase that before posting.

Thanks

**Comment by royaldelux** [comment]
Sorry for my late response, iam during the week outside the country for my work. I will reply Friday.

**Comment by royaldelux** [comment]
Hi, here is my jason file. i'm an absolute noob to raspberry and thanks to this super handy online manuals i where able to get it work so far. took me almost one complete day haha so you're talking about a "followibg package" how should i use/try this? also where to find the "homebridge's log" ?

thanks for spending you're time to this issue!

  {
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

```
"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

"accessories": [


],

"platforms": [{
    "platform": "LightWaveRF",
    "name": "LightWaveRF",
    "ip_address": "192.168.192.65",
    "manager_host": "web.trustsmartcloud.com",
    "email": "*******@*******.nl",
    "pin": "****"
}]
```

  }

**Comment by royaldelux** [comment]
![img_1614](https://cloud.githubusercontent.com/assets/22257574/18806808/9c0b514c-8237-11e6-83a2-d245dda79ddb.PNG)
![img_1615](https://cloud.githubusercontent.com/assets/22257574/18806809/9c3101f8-8237-11e6-98c4-86cfdc426eaa.PNG)

Some receivers appear as a house icon saying "niet geschikt " which means unsuitable.

**Comment by royaldelux** [comment]
![img_1616](https://cloud.githubusercontent.com/assets/22257574/18806822/2be9c0e6-8238-11e6-8e1f-e4084b409b87.JPG)
The only difference I can find is the device type "D" for a dimmer which works perfectly and the device type "O" for the normal on/off switches which obviously won't work at all.

**Comment by Cardo1** [comment]
Hi there.  A switch should be showing up as an "S" type device.  At least that's what I have on mine, which is working.  If you're using the auto config and it's not working, it may be worth copy/pasting the downloading config (at the top of your last image) and manually setting the devices to deviceType S.

**Comment by royaldelux** [comment]
Thanks for your comment! That's what I was wondering about but I'm already happy that I got it work with the auto config. I really don't know how to manually set all the devices. I found some manuals online according to this but I'll have problems creating those files.

**Comment by royaldelux** [comment]
Is there maybe a reason why the devices appear with a O instead of a S? Maybe in can fix that problem so everything will work with the auto configuration

**Comment by rooi** [comment]
Just bought some kaku switches myself. I will try to reproduce and fix this today.

**Comment by rooi** [comment]
I've changed it according the @royaldelux's suggestion. It seems to work fine in my situation. Could you test please?

**Comment by royaldelux** [comment]
Yeah! It works perfectly 👌🏻👌🏻👌🏻
