### ISSUE TITLE
gRoomNames not found

### ISSUE THREAD

**Issue by SneakyChilli** [rooi/homebridge-lightwaverf#14]
I'm installing my first Homebridge on a RPi today and have the error below, which is preventing Homebridge from starting:

pi@raspberrypi /usr/local/lib/node_modules $ homebridge
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
[9/18/2016, 2:54:54 PM] Loaded plugin: homebridge-lightwaverf
[9/18/2016, 2:54:54 PM] Registering platform 'homebridge-lightwaverf.LightWaveRF'
[9/18/2016, 2:54:54 PM] ---
[9/18/2016, 2:54:54 PM] Loaded config.json with 0 accessories and 1 platforms.
[9/18/2016, 2:54:54 PM] ---
[9/18/2016, 2:54:54 PM] Loading 1 platforms...
[9/18/2016, 2:54:54 PM] [LightWaveRF] Initializing LightWaveRF platform...
[9/18/2016, 2:54:54 PM] [LightWaveRF] LightWaveRF Platform Plugin Version 0.0.7
[9/18/2016, 2:54:54 PM] [LightWaveRF] Fetching LightWaveRF switches and dimmers...
[9/18/2016, 2:54:55 PM] Loading 0 accessories...
Receiver socket listening 0.0.0.0:9761
gRoomNames not found

Heres my config.json:

{
    "bridge": {
        "name": "Homebridge RPi",
        "username": "CC:22:3D:E3:CE:3F",
        "port": 51826,
        "pin": "123-45-155"
    },

```
"description": "Home",

"accessories": [
],

"platforms": [
   {
     "platform": "LightWaveRF",
     "name": "LightWaveRF",
     "ip_address": "192.168.2.12",
     "manager_host": "lightwaverfhost.co.uk",
     "email": "XXXXXXX@XXXXXXXX.com",
     "pin": "XXXX"
   }   
```

   ]
}

Any ideas?

Thanks

**Comment by rooi** [comment]
Does you login work on the lightwaverf site? This uses the old link with four digit pin.
The new link is not support yet (but there is a PR which almost seems finished). For now you can specify your devices manually as specified in the readme (that is if you have the new lightwaverf or kaku link).

Does this help?

**Comment by SneakyChilli** [comment]
Hi,

My login works on https://manager.lightwaverf.com/room-list, is that the right place to try? (It's a 4 digit pin).

I have the old link box with the lcd display. Can I manually setup rooms on it?

Thanks

**Comment by SneakyChilli** [comment]
BTW: I'm seeing some other folks with the same issue here:

https://github.com/nfarina/homebridge/issues/760

**Comment by bigc847** [comment]
Is there any progress on this?  I have the same issue.

I've just done a clean build of Raspian Jessie on a Pi 3, Node 4.5.0 (as that seemed to be stable and I had issues with 6.x) and get the same gRoomNames not found.

It looks like it's not connecting to the service, as replacing the PIN in config with jibberish gives the same response.

Might try and add the config manually...

**Comment by stuartridout** [comment]
Hi,

I am also having the same gRoomNames error message and I have an older link with the LCD screen.  I have had LightWaveRF kit for ages but log into the manager site with a password rather than a PIN.

Am I doing something wrong?

Stuart

**Comment by rooi** [comment]
Could you try if the manual setup works? Something like:

"platforms": [
        {
            "platform" : "LightWaveRF",
            "name" : "LightWaveRF",
            "ip_address": "10.0.1.30",
            "devices": [
                {
                    "roomId": 1,
                    "roomName": "LivingRoom",
                    "deviceId": 1,
                    "deviceName": "MyLight",
                    "deviceType": "D"
                },
                {
                    "roomId": 1,
                    "roomName": "LivingRoom",
                    "deviceId": 2,
                    "deviceName": "MyLight",
                    "deviceType": "D"
                }
            ]
        }
]

**Comment by SneakyChilli** [comment]
Manual config works fine for me. Thanks.
