### ISSUE TITLE
Everything in default room

### ISSUE THREAD

**Issue by stuartridout** [rooi/homebridge-lightwaverf#15]
Hi

I can't get homebridge to pick up my rooms and devices so I'm trying to configure them manually.  I've got a few but they are all in "Default Room" on the Home app and I can't move them.  

Is there anything I can do?  Am I doing something wrong?

Thanks

**Comment by jamieburchell** [comment]
You should be able to create new rooms from the Home app and then move your devices in to them.
1. Tap "Rooms" at the bottom of the app
2. Tap the top left menu icon
3. Tap "Room Settings..."
4. Tap "Add Room..." and add your new room name and details
5. Long-press on one of the accessories that you would like to move
6. Tap "Details"
7. Tap "Location" and choose a room 

Once all of the accessories have been moved out of "Default Room" that room will disappear.

It's a bit of a faff (and adding rooms isn't an entirely obvious process).
