### ISSUE TITLE
Small correction to website documentation

### ISSUE THREAD

**Issue by jamieburchell** [rooi/homebridge-lightwaverf#16]
This:

> For Mac OSX, (nix, or rPi - can anyone verify?) in a Terminal Window, run echo -ne '100,!Fp.' | nc u 192.168.yyy.xxx 9760 be sure to select the right IP address. Ctrl+C to close the Echo window For Windows PC

Should be:

> For Mac OSX, (nix, or rPi - can anyone verify?) in a Terminal Window, run echo -ne '100,!F*p' | nc -u 192.168.yyy.xxx 9760 be sure to select the right IP address. Ctrl+C to close the Echo window For Windows PC

Note the registration command correction

https://www.npmjs.com/package/homebridge-lightwaverf

**Comment by rooi** [comment]
changed it
