### ISSUE TITLE
Dimming with Siri & Dimming with sliders

### ISSUE THREAD

**Issue by warrenbuckley** [rooi/homebridge-lightwaverf#17]
When using Siri `Dim my ceiling lights to 50%` the command is sent as my lights briefly dim to 50% & a second or two later the light is set back to full brightness.

In addition to changing the dimming manually using the iOS10 Home app light slider. When changing from say 100% to 50% it seems to change the brightness in harsh noticeable steps, where compared to using the LightWaveRF to do the same thing the brightness is dimmed gradually to the set percentage.

Kudos on writing this plugin @rooi for HomeBridge & hopefully it would be nice to think this is no longer needed when the LightWaveRF team _finally_ release official support.

**Comment by rooi** [comment]
@warrenbuckley Thanks, I noticed this as well one time. I'll try to investigate this soon

**Comment by rooi** [comment]
Should work much better now. Could you try it yourself?

**Comment by warrenbuckley** [comment]
I have updated again with `sudo npm install -g homebridge-lightwaverf` rebooted homebridge on my laptop and now this does not pick up or register any commands to the lights at all.

So I am currently unable to test this. I can verify that homebridge is booted up fine & working as the nest homebridge proxy plugin is working just fine, reporting status & updating correctly.

LightWaveRF App displays the Link box running version `N2.91Z`

**Comment by Cardo1** [comment]
Sounds similar to what I had. Try restarting your Link, see if it updates its firmware. Mine is at 2.93Q.

**Comment by warrenbuckley** [comment]
Thanks @Cardo1 will reboot it tomorrow & try again

**Comment by warrenbuckley** [comment]
OK I haven't had time until now to try this. I rebooted the link box @rooi & @Cardo1 
Fired up HomeBridge again and tried a simple turn on of a light and it does not work & simply get no response via Home iOS app.

When the command is happening from iOS to HomeBridge. Stuff is being logged to the console but no operation actually happens.

```
Sending message: 001,!R1D1FdP32|
Sending message: 002,!R1D1FdP32|
```

Homebridge is working as I can correctly see the Homebridge nest plugin working as expected.
Normal control via the light switch & via the LightWaveRF app works.

On the original note of this - I am wondering if you need to do some kind of rate limiting. As dragging the slider shows a lot of commands in the console and only send perhaps one % change.

As I suspect flooding the LightWaveRF API with changes takes a little while to respond & thus getting the harsh, stepped dimming effect perhaps? What do you think @rooi ??

**Comment by rooi** [comment]
@warrenbuckley Sorry for the late reply. I've been really busy...

Yo mention that the commands are send/printer to the log. Something in the link to the bridge must be going wrong. Can you double check the obvious things, like the ip of the link is correct and please check the link's display when you send command. Perhaps you have to allow the device running homebridge to send udp command (again for some reason).

I just checked. Dragging the slider in apple's home app does causes multiple messages. The older home app by @brutella does not have this behaviour. Nevertheless it still works in my setup, but I agree it is not want one would want. I'll try to come up with a fix in the following week or so.

**Comment by JangoBritt** [comment]
I think I have the inverse problem to the OP... Using the Home App, when the lights are off, and I dim them on to say %5, they flash up to 100%, and then down to the desired level. :-(
