### ISSUE TITLE
Pairing the LightWaveRF Bridge

### ISSUE THREAD

**Issue by metalshark** [rooi/homebridge-lightwaverf#2]
Before commands work the bridge needed pairing. This might be best served returning an error if a command is unsuccessful and entering a "pairing mode" where commands are queued until successful?

Looking at the errors in the console I used a script similar to the following (replaced with my details). As node-lightwaverf has a few more updates than are available from npmjs I had to use the git version. Below is the code I used (required editing node-lightwaverf to use lightwaverfhost.co.uk).

var LightwaveRF = require("lightwaverf");
var lw = new LightwaveRF({ip:"192.168.1.123",email:"name@host.com",pin:"0123"});
lw.sendUdp('!F*p', function (response) {
  console.log(response);
});

Hopefully this will be of use to anyone else.

**Comment by ghost** [comment]
Hi @metalshark , how would I go about doing this from a raspi on Raspbian ? I seem to have everything working but when I send a command the Link (old LCD screen version 2.9 software) does not come up with a registration screen and nothing happens , I also get no errors. I assume I need to pair it but am not sure how.

**Comment by metalshark** [comment]
Hey there,

I too have an old one with an LCD screen.

When I used this plugin the commands also wouldn't work.

You have to send a UDP message to make the registration Yes/No appear on
the screen and accept the Raspberry Pi.

Modifying the script (entering your details into it) and calling it pair.js
then running it on the Raspberry Pi should let you get going with this
plugin.

**Comment by ghost** [comment]
Perfect thank you!
(To anyone else reading this I installed paulys lgightwaverf gem and then used the above pair.js script)

**Comment by d900man** [comment]
I also need to pair with my Wifi Link, can somebody please help me with the pair.js file.

I need help with making it where to save it and how to send it to the wifi link.

I have homebrigde installed and also rooi homebridge - lightwaverf plugging installed. 

Thanks

**Comment by JangoBritt** [comment]
More details on this in the readme.md now, can this issue be closed?

**Comment by metalshark** [comment]
It might be worth mentioning you need to install netcat on Linux for the OS
X command to work as well.

Alternatively do it natively in nodejs (pair.js does this) and send that
command automatically if you receive an authorisation failed for any
action, as HomeBridge may be running on a headless device where running
additional commands manually is a small pain for many we can save them
from (has to be run from the device that is issuing commands). I would be
tempted to do this and add a flag to disable the behaviour.

If you like the latter approach I don't mind sending a patch at the weekend.

**Comment by rooi** [comment]
@metalshark a patch would be great. Are you able to test it though? Can you unpair a device, or will you use a different one?

**Comment by metalshark** [comment]
@rooi I'll just change my IP and MAC address to test.

Only have the older LCD unit (great for seeing your electricity consumption
at a glance) to test against. Is there any difference in the pairing
between the two or the error response when unpaired?

No problems it'll be my pleasure to coder it up, as that'll hopefully save
the bug being re-opened, etc

**Comment by metalshark** [comment]
Unfortunately I cannot get an unauthorised error back from the UDP
requests. Is there a request where we can get an error returned?

**Comment by JangoBritt** [comment]
I read somewhere that if you send your command and tell it to listen on 9781, you'll get a response.

**Comment by metalshark** [comment]
Am going to need this weekend too to finish off, however I am getting
responses :-)

**Comment by rooi** [comment]
@metalshark did you get it to work? Thanks!

**Comment by jprdupont** [comment]
On my setup, this was a result of having too many devices paired with my lightwaverf link. I did a factory reset on the box then had no problem connecting with nc.
['new' lightwave link manual pdf](https://lightwaverf.com/wp-content/uploads/2016/06/LW930.pdf)
