### ISSUE TITLE
Commands appended with | not accepted by Link

### ISSUE THREAD

**Issue by lightwaverf** [rooi/homebridge-lightwaverf#21]
Hi, 

I've managed to get the plugin up and running with some of my devices as below; 

`{
"platform": "LightWaveRF",
"name": "LightWaveRF",
"ip_address": "10.0.1.101",
"devices":

[{
"roomId": 1,
"roomName": "LivingRoom",
"deviceId": 1,
"deviceName": "RedLamp",
"deviceType": "D"
},
{
"roomId": 1,
"roomName": "LivingRoom",
"deviceId": 2,
"deviceName": "BrownLamp",
"deviceType": "D"
},
{
"roomId": 1,
"roomName": "LivingRoom",
"deviceId": 1,
"deviceName": "Uplighter",
"deviceType": "D"

}]
`
I have successfully registered my MacBook (running Homebridge) with my Wifi Link (old one with screen). 

When clicking the buttons within Home App on my iPhone I see the below, indicating that a UDP packet has been sent: 

Sending message: 001,!R1D2F1|
Sending message: 002,!R1D1F1|
Sending message: 003,!R1D2F0|

However it is not doing anything. 

If I send the command using PacketSender nothing happens either. 

HOWEVER... if I drop the | OR include || it works. 

I suspect this is because of the ability to include words to be displayed on the LCD screen e.g.; 

001,!R1D2F0|Lamp|Off

Am I the only one seeing this, is there anything I can modify to send 2 pipes or drop one?

Thanks

**Comment by rooi** [comment]
Hi,

Perhaps you can for this module: https://github.com/rooi/node-lightwaverf/blob/master/index.js
And change this function to include the | at the end: LightwaveRF.prototype.sendUdp

I cannot test it myself right now, perhaps this Sunday. Let me know how it goes though.

**Comment by lightwaverf** [comment]
Thanks, that helped in the sense it is now sending the right command, but I think I am seeing the same issue as 22 - seems to lock up homebridge. 

The fun continues :)
