### ISSUE TITLE
1 light keeps crashing homebridge

### ISSUE THREAD

**Issue by gizbod** [rooi/homebridge-lightwaverf#22]
Rooi,
I wonder if you could shed any light on why 1 of my dimmers keeps crashing homebridge.
Every time i try to turn off this particular dimmer via the app or siri it will not turn off and subsequently none of the lightwave products work through homebridge until i take the power from the wifi link and plug it back in.
its all set up the same way as everything else etc.
can't figure it out..

**Comment by rooi** [comment]
Hi, 

can you post your homebridge log (check for passwords and erase them). Thanks!

Roy

**Comment by gizbod** [comment]
il look, not sure of the file path on RPi

**Comment by gizbod** [comment]
Roy,
im not sure where to find the full log, but i can tell you that when sending the command via the app, terminal sends the same command just like the other lights etc. nothing shows any different. 
unless you or anyone can tell me where to find the log.

**Comment by rooi** [comment]
Do you have a console output that prints the udp message? Please post that along with your config file, maybe there is something in there that points out the problem

If you don't have the log, you can try the following. I'm not sure where the log is located on a Pi, but it you disable the auto-run daemon and run in manually in a console window, you should see a log. Another option is to run homebridge in debug mode with: DEBUG=\* homebridge -D

**Comment by rooi** [comment]
O wait, maybe you can find the log using this: https://github.com/nfarina/homebridge/wiki/Basic-Trouble-Shooting
