### ISSUE TITLE
G -> option not supported by iOS 

### ISSUE THREAD

**Issue by PencilDH** [rooi/homebridge-lightwaverf#24]
Hi, 

I am not sure if it's me or not, but I set up my device as 'G' and on iOS it shows up as not supported? Is it because I did something wrong?

The device is a window blinds controller - I have it working fine with lightwaverf app

**Comment by PencilDH** [comment]
Hello anybody here? Has anyone got any expirence with this?

**Comment by rooi** [comment]
Hi @PencilDH,

Sorry for the late reply, I was abroad on holiday.
Could you please provide more details? What iOS version are you using? What homebridge version etc.
Perhaps also include a homebridge log (remember to erase passwords which may be in the log).

Thanks!

Roy

**Comment by R4ffles** [comment]
Hi, So Rooi wrote the Garage door option after I asked him how I could control my Garage door with his Lightwaverf code. My setup is a Lightwaverf Link with over 20 Dimmers, Sockets, Switches and Relays. The Garage door is controlled by a Lightwaverf JSLW821 in-Line relay (Open/Sop/Close) and the code used in my config.json file is below (30 is the time it takes in seconds to open or close the roller shutter)
I assume other Lightwaverf devices are working fine on homebridge and that the item works fine on the lightwaverf app.

{   
                   "roomId": 8,
                   "roomName": "Garden",
                   "deviceId": 4,
                   "deviceName": "Garage Door",
                   "deviceType": "G",
                   "timeOut": 30
               },

If it is not working and you have the same relay, then try checking the roomID number (count from top left (1), top right (2), left down one row (3) etc and then check the deviceID number (simply count from top to bottom) not an exact science as unlinking items can leave some numbers unused. If that still doesn't work try going through each number one by one. You can also try sending a command to the Lightwaverf link from your PC or MAC

**Comment by PencilDH** [comment]
Hi, Thanks of the messages

So I have it set up the same as you 
{
"roomId": 4,
"roomName": "Bedroom",
"deviceId": 11,
"deviceName": "Blinds",
"deviceType": "G",
"timeOut": 20
},

When I change the device type to "S" and remove time out the device responds to "on" / "off" commands. In Switch mode its also working with HomeApp and SIRI (the device changes from not supported to a switch), its just a bit stupid saying blinds on/off....


The problem is in iSO 10.2.1

I will check the other details in the evening 
![img_0006](https://cloud.githubusercontent.com/assets/19908009/23169006/117a80d0-f842-11e6-8b4b-d98c729182f3.PNG)
![img_0005](https://cloud.githubusercontent.com/assets/19908009/23169025/234dfee0-f842-11e6-9f48-dc1acc717aa8.PNG)

**Comment by R4ffles** [comment]
Hi, am also on 10.2.1
So if you have the jsjlw821 it should work. Have you got the latest code from rooi?

**Comment by andygroves** [comment]
Hi,

I tried that and got the error. Ill check it again.

I may be have around 30 devices in different rooms, and identify the device id from the lightwaverf manager.

Does the time function work with other switches or can it.

I think the timer function would be great for exit routes when leaving or entering a geo space or even for sceens.

Regards,

Andy G.

**Comment by PencilDH** [comment]
sorry what is ROOI? -> ** Update** Sorry I got you now, I reinstalled everything about 2 months a go need to check the version

I a quite interested to figure out why its not working... On the LW web app its working fine thus I think its nothing to do with he device but rather Homebridge/pluging IOS

<img width="323" alt="screen shot 2017-02-21 at 14 49 03" src="https://cloud.githubusercontent.com/assets/19908009/23169836/2450f646-f845-11e6-83e6-42e5285b024a.png">


To make it a bit more complicated I don't have the jsjlw821 its a home made device, but as far as I am aware LW protocol is a single direction protocol so it should matter what device I use? As the JSJSLW930 bridge only broadcasts out commands and its up the slave devices to filter out and check its the message is for designated for it or not ?

**Comment by andygroves** [comment]
Hi Pencil,

The LWRF box can be both Single way and Bi-directional.

The heating switches and thermostats are bi-directional, the current switches are as you say one way.

I have both switch and heating on the system.

Regards,

Andy G

**Comment by R4ffles** [comment]
If the blinds work in "S" mode then you must have the right deviceid.

I doubt the timeOut would work with other types but that's a question for
rooi

You can achieve the same using scenes and timers and I use the eve app and
the home app to create complex scenes.

I have the garage and outside lights come on if it's after sunset and the
garage door is opened as an example

**Comment by andygroves** [comment]
Hi Raffles,

I thought similar, is possible to get access to the event in lwrf from homebridge/homekit.

Thanks,

Andy G

**Comment by PencilDH** [comment]
@R4ffles not too bothered about the time out my blinds do the logic and know when to stop or start as I'm implement some feedback and force sensing...  I am currently looking to do a second revision of my blinds controller  for other rooms but that is for a different thread...  

I used Siri a lot and I think its stupid saying brings on/off that bothered me the most, also the fact that it should work but it doesn't .....

**Comment by R4ffles** [comment]
Rooi is Roy Arents who wrote the Homebridge-LightwaveRF plugin.

If you don't have the jsjslw821 it won't work because that inline relay has
a special stop mode with a matching on/off/stop switch. Other relays are
only on/off

**Comment by R4ffles** [comment]
Andy, I am not a techie, thats a question for the author rooi

**Comment by PencilDH** [comment]
@R4ffles Sorry I think you might be incorrect or I am missing something, could you explain why won't it work?
I am almost 100% sure it will work, as my hardware is compliant with the LW protocol - I spent some time working on this and getting quite deep in to the protocol

**Comment by andygroves** [comment]
Hi,

Yes sorry im sort of a nerd, though grant set up my pi setup.

Quite new to the home automation though home bridge though.

Hopefully, Rooi, may see this in his good time.

Thanks,

Andy G.

**Comment by R4ffles** [comment]
Pencil, do your blind stop half way through if you press the stop button on the lightwaverf app? if they do, do you know what the udp command for the blinds is? should look like this

echo -ne '001,\!R8D4F^\r' | nc -u -w1 10.0.0.69 9760

F( or F) is the open/close command for the inline relay.

Open and Close commands can be sent to the JSJSLW821 (500W relay) only. Dimmer and on/off devices will ignore any open, stop or close commands. The commands are F( for open, F) for close and F^ for stop.

Taken from Lightwaverf's website, so do your blinds get sent R1D1F1 or R1D1F0 instead?

**Comment by rooi** [comment]
Wow this has turned into some conversation.

I'm not sure if I can follow everything correctly, but these may be some things to check:

@PencilDH : Could you please check if you have a recent version of homebridge? The screenshots you've included and the iOS version indicate these should support blinds. The only thing I can think of now is the homebridge and/or hap-nodejs version. You can use the following command:

npm -v homebridge
I'm on 3.10.9 and hope to upgrade soon... If you update or install homebridge, please note the -g option to prevent mixing up versions and such (sudo npm install -g --unsafe-perm homebridge)

@andygroves : The receiving device should work with homebridge and this plugin if it works with a LightwaveRF Link transmitter (though the app, or web interface). I've only tested with KAKU's ics-1000, but the lightwave link should work as well. The only thing is that you need to figure out the correct device id if you're one the newer devices (the old devices/webinterface allow to get them directly).

Does this help?

**Comment by andygroves** [comment]
Hi Rooi,

First of all great work, user called grant sent me up, and I suffer withdrawal symptoms if it every go down.
I have the old LightwaveRF LW500WH box.
Some random questions if possible please.
Have you thought about,
adding the heating device to LWRF
Adding access to the light wave rf

Regards,
Andy Groves

**Comment by PencilDH** [comment]
HI everyone - Sorry for all this commotion, it works now, but I needed to reinstall home bridge and update the plugins!

Just a quick one saying Close Bedroom Blinds doesn't seem via Siri : I get a Sorry I wasn't able to find any shades in the bedroom at this time ?!

Close / Open Garage door works now!

I guess IOS doesn't like me calling a garage door : blinds 

@rooi would it be easy to add another type of device? I looked in the HomeKit spec R8 and Window Covering device class would work :)

@R4ffles Yes my blinds stop when you press stop too... but I am not sure if I follow what you meant I am new to the home bridge side of things, I usually deal more with hardware than software 
if you interested in the RF stuff please this is a good starting point 
https://wiki.somakeit.org.uk/wiki/LightwaveRF_RF_Protocol

**Comment by R4ffles** [comment]
Glad you got it working, mostly. I did wonder if the home app/siri would
recognise blinds as the association is with the garage door device.

Seems that's the case, not sure if rooi can create a new device type of
"blinds" using the same code as for the garage door but if he could that
would make it more useable.

Btw, what are you using in place of the jsjslw821?

**Comment by PencilDH** [comment]
I have had a quick look at the code and I think 
A. Window covering specifications are basically declared in NodeJS, but I think you need to create some additional modules for this device type to work properly,
B. After that is done the the lightwave RF plugin can be modified 

I have no idea how to work with this code, could someone give me a quick few pointers how to starts?
what IDE is best used and how to setup the whole home bridge project on my machine so I can try to develop something? 

Is there like a started guide how to get going?

**Comment by rooi** [comment]
@andygroves I have an evohome system for heating myself, so I didn't think of adding lwrf heating devices. It shouldn't be to difficult though. ~if you can figure out the udp command, we can probably add it to this plugin.

@PencilDH if you fork this git repo and copy the code segments that have garage door in them and change them for blinds you should be set. You can use any text editor for this change and after changing the code, just run: "sudo npm install -g" in the cloned directory.
Once you've got it working, please send me a pull request so I can include it in this code as well.
I'm also on slack if you want a fast response.

**Comment by andygroves** [comment]
Hi Rooi,

Wow rooi, thanks for the positive response, im sure icould send you a beer for your effort.

Sure ill provide what ever I can to help.

Have you ever seen this page reading from a mobile api.lightwaverf.com

In in the process of read now.

You can contact be direct if you choose, andygroves@live.co.uk<mailto:andygroves@live.co.uk>, I also use google hangouts, andygroves70@gmail.com<mailto:andygroves70@gmail.com>

Regards,

Andy G

**Comment by andygroves** [comment]
Hi Rooi,

Also have you thought about adding access to events etc, via home kit.

Regards,

Andy G

**Comment by rooi** [comment]
@andygroves thanks for the link to the api! I think I spoke to soon, unfortunately. The heating methods in lightwaverf are significantly more difficult than the lights and garage door. They now seem to use two way communication with json messages. The lights and  garage door use simple udp command.
Implementing this is much more work and one would need a heating device to do so. I could not find others that have implemented this and use it in this project... Long story short, I don't think this can be implemented soon. Hopefully someone with a heating device and nodejs knowledge will implement something which we can use.

**Comment by rooi** [comment]
@andygroves what events do you mean? I only use lights in my setup and hook up homekit events to control them. My light respond to me getting home after sun down and me saying goodnight to siri. The light switches I have do not give any response when the switches are pressed, unfortunately, so I cannot get an event from this either.

**Comment by andygroves** [comment]
Hi Rooi,

Do you use the lighwave app, in the app events can be built and timmer can be triggered and assigned.

LWRF switch have Moods or screens, am I making sense now.

Thanks,

Andy G

**Comment by andygroves** [comment]
Hi Rooi,

Yes the heating devices are two way, the trv can fire data both ways.

The temperature and schedule can be programmed via the TRV/thermostat, a web app or phone lwrf app and cross read by each one.

The lwrf app and web page can control the trvs and display the current temperature.

Have you seen the energy monitors by LWRF I also use them to, can they be added may be?

I have the heating devices, but defiantly no node knowledge, vb6 may be, sorry.

If you do get time to investigate it in the future, id do what ever I can do to help.

Im certainly happy for you to have access to my pc network etc via team viewer if you’re interested, in the future.

Thanks,

Andy G

**Comment by PencilDH** [comment]
@andygroves I don't want to be a party pooper but please keep the discussion within the correct issues.

My problem turns out not me being a fool and not updating the plugin... thus I feel strongly that issue should be closed

**Comment by andygroves** [comment]
Hi Pencil,

Sorry, did not mean to take over a problem more over I was expanding a wider discussion of functionality.

I apologise for breaking protocol, Ive never used this site or forum before.

Could you tell me the appropriate place to raise function / feature requests.

Regards,

Andy G.
