### ISSUE TITLE
Feature Request (Is it Ok Here)

### ISSUE THREAD

**Issue by andygroves** [rooi/homebridge-lightwaverf#25]
1, Add feature to enable LWRF heating devices.
2, Add feature to enable access to the LWRF moods/scenes.
3, Add feature to enable access to the LWRF timers.

**Comment by PencilDH** [comment]
Hi Andy:
1 -> I have not much to say, maybe you can try yourself, I think this is not an easy task if one doesn't have the hardware to reverse engineer and test the protocols. Maybe try doing it yourself?
2 -> Add feature to enable access to the LWRF moods/scenes. you can build moods via the automations in the HomeKit app
3-> Again HomeKit app has this feature, and more as you can use geotagging or triggers.

**Comment by AKWillows** [comment]
Hi @PencilDH 

On your point two - I accept that you can build moods using HomeKit... However, and this may just be an issue which affects me, when using moods in HomeKit which control more than a few Lightwave devices, I find that some devices "miss" the command. I wonder if this is down to the fact that Homebridge fires the commands too quickly for the LightwaveHub to send them? I think the Lightwave API suggest leaving three seconds between commands, although I have found that it can usually deal with them quicker than this. So, for example, being able to send the Lightwave "All Off" command for a room via the plug in would be useful
