### ISSUE TITLE
Adding Window Covering Service

### ISSUE THREAD

**Issue by PencilDH** [rooi/homebridge-lightwaverf#26]
Hi rooi,

I have been quite busy lately, but I now got myself around to get a stab at adding a new device type.

We previously talked about me having a go adding WC function to work the same way as garage opening.

Would you be able to explain to me where is the definition of the device coming from? I am a bit confused about the structure of the plugin?

you define :
```js
this.isGarageDoor = (device.deviceType.indexOf('G') > -1);
```
Can I just define?
```js
this.isWindowCovering = (device.deviceType.indexOf('WC') > -1);
```

As I understand there needs to be some sort of definition of WC in HAP-NodeJS?
Which file in this project would have the relevant definitions for making WC work?

WindowCovering service is defined in lib/gen/HomeKitType.js l.3208 is this enough?
Or additional things need to be written to make this work?

I have no idea I where to start on this, its my first couple of hours today spent on trying to get it working, so any tips would be appreciated....

I have invited you to the slack channel I created too :) 

Speak soon

**Comment by rooi** [comment]
Hi, @PencilDH,

The original device type originated from the old lightwaverf specification. I don't have all type of devices and am not sure if they are supported in the old specification so I just made up new ones (probably the same with garage door). Just defining WC should be fine.

You're right about adding a new device type. Just add the service and some specific functions that handle it and you should be ready to go. You probably need specific lines of code for every entry of 'door' or 'garage' in the code.

I just saw you're new slack channel. You can contact me there as well (probably you'll get a faster reply if the slack app works better than the last couple of days)
