### ISSUE TITLE
where have i gone wrong!

### ISSUE THREAD

**Issue by atariboy2** [rooi/homebridge-lightwaverf#29]
[5/4/2017, 9:24:45 PM] Loaded plugin: homebridge-lightwaverf
[5/4/2017, 9:24:45 PM] Registering platform 'homebridge-lightwaverf.LightWaveRF'
[5/4/2017, 9:24:45 PM] ---
[5/4/2017, 9:24:45 PM] Loaded config.json with 0 accessories and 1 platforms.
[5/4/2017, 9:24:45 PM] ---
[5/4/2017, 9:24:45 PM] Loading 1 platforms...
[5/4/2017, 9:24:45 PM] [LightWaveRF] Initializing LightWaveRF platform...
[5/4/2017, 9:24:45 PM] [LightWaveRF] LightWaveRF Platform Plugin Version 0.1.2
[5/4/2017, 9:24:45 PM] [LightWaveRF] Fetching LightWaveRF switches and dimmers...
Receiver socket listening 0.0.0.0:9761
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: write EPROTO 140736785351616:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

    at exports._errnoException (util.js:1034:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:812:14)
Neils-Mac-mini:~ withdesign$

**Comment by Solublepeter** [comment]
I have this issue too. Same error message apart from the last bit

```
    at exports._errnoException (util.js:1018:11)
    at WriteWrap.afterWrite (net.js:800:14)
```

**Comment by lupe** [comment]
Just setting up a Pi to run Homebridge for Lightwave and getting this same error.

- Old Style Lightwave Link (I think - old is the one with the LCD Screen right?)
- Have Paired the Pi with the link via a packet echo.
- Running on Jessie

**Comment by rooi** [comment]
Hi,

Are you able to login on one of these portals using a four digit pin?

web.trustsmartcloud.com
lightwaverfhost.co.uk

If not, then you probably have accounts on the new portal. You can still use this plugin but have to manually specify the devices (and figure out which roomID and deviceID correspond to your devices).

Does this help?

Roy

**Comment by lupe** [comment]
Hey Roy, thanks for the reply.

I've tried both of those hosts in the config.json. Is there a webpage form for those servers i can try to login on to be sure?

I can login to https://manager.lightwaverf.com/ with email & pin - is that the new portal?

**Comment by rooi** [comment]
It seems you're  on the new site.

Full links to the old ones are:
https://web.trustsmartcloud.com/manager/index.php
https://lightwaverfhost.co.uk/manager/index.php

If you cannot login there you can try the following config file format (see main readme):

"platforms": [
       {
           "platform" : "LightWaveRF",
           "name" : "LightWaveRF",
           "ip_address": "10.0.1.30",
           "devices": [
               {
                   "roomId": 1,
                   "roomName": "LivingRoom",
                   "deviceId": 1,
                   "deviceName": "MyLight",
                   "deviceType": "D"
               },
               {
                   "roomId": 1,
                   "roomName": "LivingRoom",
                   "deviceId": 2,
                   "deviceName": "MyLight",
                   "deviceType": "D"
               },
               {
                   "roomId": 1,
                   "roomName": "LivingRoom",
                   "deviceId": 3,
                   "deviceName": "MyGarageDoor",
                   "deviceType": "G",
                   "timeOut": 10
               }
               {
                   "roomId": 1,
                   "roomName": "LivingRoom",
                   "deviceId": 3,
                   "deviceName": "MyBlinds",
                   "deviceType": "WC",
                   "timeOut": 15
               }
           ]
       }
]

**Comment by lupe** [comment]
Ah ok, I did do a hard reset of the Link a few months back and re-registered it so guess it migrated me to the new host.

lightwavehost.co.uk is throwing me a deprecated SSL error, that wouldn't be causing an issue for the plugin would it?

I assume if I were to try and register the Link with the old sites i'd have to start from fresh and go back to old app etc.? Was hoping to avoid having to manually enter the devices!

Thanks again for all the help Rooi.

**Comment by rooi** [comment]
Guess they did. A while ago I tried to obtain the roomIDs and deviceIDs from the new website, but it did not work then. Perhaps you can try by logging in and checking the page its source for references to these IDs. If they are there you can also use them to create the config file for the plugin and if this works, perhaps we can automate it.

**Comment by lupe** [comment]
At work right now, but from a quick look at the source of one of the room pages it looks like they might have changed how they reference Rooms/Devices.

Device IDs (And Rooms) are now much longer, so perhaps they've made them easier to reference with a unique ID instead of having to call RoomID/DeviceID

For Example:
` data-room_id="95714" data-on_event="" data-device_type_id="1" data-value="Off" data-device_id="283979`

And the web controls also reference things like `name="onoff-301563"` which is promising (i think? i'm not much of a coder!)

Have attached source from room page
[roomsrc.txt](https://github.com/rooi/homebridge-lightwaverf/files/1029271/roomsrc.txt)
