### ISSUE TITLE
Unknown commands / devices

### ISSUE THREAD

**Issue by ghost** [rooi/homebridge-lightwaverf#3]
I've found that if you accidentally refer to a device in the wrong way , or say 'identify' it in the app , home bridge will crash and throw this error.

> Sending message: 002,!R3D2F1|
> /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
>       throw new Error("This callback function has already been called by someone else; it can only be called one time.");
>       ^
> 
> Error: This callback function has already been called by someone else; it can only be called one time.
>     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
>     at Object.responseListeners.(anonymous function).listener (/usr/local/lib/node_modules/homebridge-lightwaverf/node_modules/lightwaverf/index.js:247:5)
>     at LightwaveRF.<anonymous> (/usr/local/lib/node_modules/homebridge-lightwaverf/node_modules/lightwaverf/index.js:80:25)
>     at emitTwo (events.js:87:13)
>     at Socket.emit (events.js:172:7)
>     at UDP.onMessage (dgram.js:480:8)
>

**Comment by rooi** [comment]
Hi,

Thanks for reporting this issue. I could reproduce the identify issue and I think I've fixed it. Could you please check?
Could you please explain what you mean by refer to a device in the wrong way if this is still an issue?

Thanks!
