### ISSUE TITLE
Get permission errors when trying to install

### ISSUE THREAD

**Issue by AKWillows** [rooi/homebridge-lightwaverf#31]
Hi

Novice RaspberryPi-er here.

Have got Homebridge installed successfully using the instructions on their page.

However when I try to install this lightwave plug in using sudo npm install -g homebridge-lightwaverf, I get the following error:

_code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/rooi/node-lightwaverf.git /root/.npm/_cacache/tmp/git-clone-0c2aef16
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-0c2aef16': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-16T18_07_13_218Z-debug.log_

Any idea what is going wrong please?

**Comment by rooi** [comment]
Hi, is this the first plugin you try to install?

**Comment by AKWillows** [comment]
Yes it is. Straight after the main homebridge program. I've actually tried twice, completely reinstalling Raspian from scratch in between in case I had done something wrong the first time!

**Comment by rooi** [comment]
Could you try another plugin? This may rule the cause of this plugin out and the solution may be found in the homebridge issue history

**Comment by AKWillows** [comment]
Hi. Have now installed a couple of other plugins... homebridge-people and home bridge-config-ui and both have successfully installed. Have tried the lightwaverf plugin again and received the same failure error messages

**Comment by AKWillows** [comment]
I have resolved the issue. I did a fresh install of everything and, before installing Homebridge and this plug in, I made some changes to file permissions as detailed here https://docs.npmjs.com/getting-started/fixing-npm-permissions. Everything installed and runs fine now.
