### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by robertdijk** [rooi/homebridge-lightwaverf#34]
When I run `sudo npm install -g homebridge-lightwaverf` on my raspberry Pi it gives errors.
This is the output:
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/rooi/node-lightwaverf.git /root/.npm/_cacache/tmp/git-clone-d572b661
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-d572b661': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-11T16_23_24_108Z-debug.log

This is the 2017-10-11T16_23_24_108Z-debug.log file:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-lightwaverf' ]
2 info using npm@5.3.0
3 info using node@v8.6.0
4 verbose npm-session a70905d93aba24a8
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/homebridge-lightwaverf 175ms (from cache)
8 silly pacote tag manifest for homebridge-lightwaverf@latest fetched in 414ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule homebridge-lightwaverf@0.1.3 checking installable status
14 silly fetchPackageMetaData error for lightwaverf@git://github.com/rooi/node-lightwaverf.git Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/rooi/node-lightwaverf.git /root/.npm/_cacache/tmp/git-clone-d572b661
14 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-d572b661': Permission denied
15 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/rooi/node-lightwaverf.git /root/.npm/_cacache/tmp/git-clone-d572b661
15 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-d572b661': Permission denied
15 verbose stack
15 verbose stack     at ChildProcess.exithandler (child_process.js:271:12)
15 verbose stack     at emitTwo (events.js:125:13)
15 verbose stack     at ChildProcess.emit (events.js:213:7)
15 verbose stack     at maybeClose (internal/child_process.js:927:16)
15 verbose stack     at Socket.stream.socket.on (internal/child_process.js:348:11)
15 verbose stack     at emitOne (events.js:115:13)
15 verbose stack     at Socket.emit (events.js:210:7)
15 verbose stack     at Pipe._handle.close [as _onclose] (net.js:547:12)
16 verbose cwd /home/pi
17 verbose Linux 4.9.41-v7+
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge-lightwaverf"
19 verbose node v8.6.0
20 verbose npm  v5.3.0
21 error code 128
22 error Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/rooi/node-lightwaverf.git /root/.npm/_cacache/tmp/git-clone-d572b661
22 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-d572b661': Permission denied
23 verbose exit [ 1, true ]

I can use npm to install other plugins. I have the newest version of git and npm version 5.4.2

**Comment by MartinKlefas** [comment]
I had this error too - apparently it's something to do with directory permissions - and only happens with some packages.

It can be resolved with the below command:
 sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

If you then run npm -g install homebridge-lightwaverf with no sudo

Problem is that I then run into more errors:
pi@raspberrypi ~ $ npm -g install homebridge-lightwaverf

> fibers@2.0.0 install /usr/local/lib/node_modules/homebridge-lightwaverf/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory '/usr/local/lib/node_modules/homebridge-lightwaverf/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
In file included from /home/pi/.node-gyp/6.7.0/include/node/node.h:42:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/pi/.node-gyp/6.7.0/include/node/v8.h:345:1: error: expected unqualified-id before 'using'
/home/pi/.node-gyp/6.7.0/include/node/v8.h:481:1: error: expected unqualified-id before 'using'
/home/pi/.node-gyp/6.7.0/include/node/v8.h:882:1: error: expected unqualified-id before 'using'
/home/pi/.node-gyp/6.7.0/include/node/v8.h:5431:35: error: 'virtual v8::EmbedderHeapTracer::~EmbedderHeapTracer()' declared virtual cannot be defaulted in the class body
../src/fibers.cc:68:2: error: 'Handle' does not name a type
../src/fibers.cc:72:2: error: 'Handle' does not name a type
../src/fibers.cc:94:2: error: 'Handle' does not name a type
../src/fibers.cc:104:2: error: 'Handle' does not name a type
../src/fibers.cc:126:58: error: 'Handle' has not been declared
../src/fibers.cc:126:64: error: expected ',' or '...' before '<' token
../src/fibers.cc: In function 'void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)':
../src/fibers.cc:127:29: error: 'handle' was not declared in this scope
../src/fibers.cc: At global scope:
../src/fibers.cc:139:26: error: variable or field 'SetInternalPointer' declared void
../src/fibers.cc:139:26: error: 'Handle' was not declared in this scope
../src/fibers.cc:139:34: error: expected primary-expression before '>' token
../src/fibers.cc:139:36: error: 'handle' was not declared in this scope
../src/fibers.cc:139:44: error: expected primary-expression before 'int'
../src/fibers.cc:139:55: error: expected primary-expression before 'void'
../src/fibers.cc:143:27: error: template declaration of 'void* uni::GetInternalPointer'
../src/fibers.cc:143:27: error: 'Handle' was not declared in this scope
../src/fibers.cc:143:35: error: expected primary-expression before '>' token
../src/fibers.cc:143:37: error: 'handle' was not declared in this scope
../src/fibers.cc:143:45: error: expected primary-expression before 'int'
../src/fibers.cc:148:2: error: 'Handle' does not name a type
../src/fibers.cc:153:14: error: variable or field 'Return' declared void
../src/fibers.cc:153:14: error: 'Handle' was not declared in this scope
../src/fibers.cc:153:22: error: expected primary-expression before '>' token
../src/fibers.cc:153:24: error: 'handle' was not declared in this scope
../src/fibers.cc:153:32: error: expected primary-expression before 'const'
../src/fibers.cc:157:14: error: variable or field 'Return' declared void
../src/fibers.cc:157:14: error: 'Handle' was not declared in this scope
../src/fibers.cc:157:22: error: expected primary-expression before '>' token
../src/fibers.cc:157:24: error: 'handle' was not declared in this scope
../src/fibers.cc:157:51: error: expected primary-expression before 'info'
../src/fibers.cc:165:2: error: 'Handle' does not name a type
../src/fibers.cc:169:2: error: 'Handle' does not name a type
../src/fibers.cc:173:2: error: 'Handle' does not name a type
../src/fibers.cc:177:2: error: 'Handle' does not name a type
../src/fibers.cc:181:2: error: 'Handle' does not name a type
../src/fibers.cc:185:2: error: 'Handle' does not name a type
../src/fibers.cc:195:2: error: 'Handle' does not name a type
../src/fibers.cc:377:17: error: expected ';' at end of member declaration
../src/fibers.cc:377:30: error: expected ')' before '<' token
../src/fibers.cc:383:15: error: expected ')' before '<' token
../src/fibers.cc:649:3: error: 'Handle' does not name a type
../src/fibers.cc:813:20: error: 'Handle' has not been declared
../src/fibers.cc:813:26: error: expected ',' or '...' before '<' token
../src/fibers.cc: In static member function 'static void Fiber::DestroyOrphans()':
../src/fibers.cc:464:30: error: 'Deref' is not a member of 'uni'
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::New(const Arguments&)':
../src/fibers.cc:486:5: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:486:5: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:486:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:488:5: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:488:5: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:488:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:490:5: error: 'Handle' was not declared in this scope
../src/fibers.cc:490:17: error: expected primary-expression before '>' token
../src/fibers.cc:490:19: error: 'argv' was not declared in this scope
../src/fibers.cc:491:24: error: 'NewInstance' is not a member of 'uni'
../src/fibers.cc:491:64: error: 'Deref' is not a member of 'uni'
../src/fibers.cc:491:134: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:494:4: error: 'Handle' was not declared in this scope
../src/fibers.cc:494:19: error: expected primary-expression before '>' token
../src/fibers.cc:494:21: error: 'fn' was not declared in this scope
../src/fibers.cc:494:41: error: expected primary-expression before '>' token
../src/fibers.cc:494:42: error: '::Cast' has not been declared
../src/fibers.cc:495:31: error: 'GetCurrentContext' is not a member of 'uni'
../src/fibers.cc:496:40: error: no matching function for call to 'Return(v8::Local<v8::Object>, const Arguments&)'
../src/fibers.cc:496:40: note: candidate is:
../src/fibers.cc:161:7: note: template<class T> void uni::Return(v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, uni::GetterCallbackInfo)
../src/fibers.cc:496:40: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::Run(const Arguments&)':
../src/fibers.cc:504:38: error: no match for call to '(Fiber) (v8::Local<v8::Object>)'
../src/fibers.cc:510:5: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:510:5: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:510:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:512:5: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:512:5: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:512:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:523:6: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:523:6: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:523:6: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:533:52: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Local<v8::Value>)'
../src/fibers.cc:533:52: note: candidate is:
../src/fibers.cc:126:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:535:52: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc:535:52: note: suggested alternatives:
/home/pi/.node-gyp/6.7.0/include/node/v8.h:8532:18: note:   'v8::Undefined'
/home/pi/.node-gyp/6.7.0/include/node/v8.h:8532:18: note:   'v8::Undefined'
../src/fibers.cc:539:28: error: 'class Fiber' has no member named 'ReturnYielded'
../src/fibers.cc:539:49: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::ThrowInto(const Arguments&)':
../src/fibers.cc:546:38: error: no match for call to '(Fiber) (v8::Local<v8::Object>)'
../src/fibers.cc:549:5: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:549:5: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:549:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:551:51: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc:551:51: note: suggested alternatives:
/home/pi/.node-gyp/6.7.0/include/node/v8.h:8532:18: note:   'v8::Undefined'
/home/pi/.node-gyp/6.7.0/include/node/v8.h:8532:18: note:   'v8::Undefined'
../src/fibers.cc:553:51: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Local<v8::Value>)'
../src/fibers.cc:553:51: note: candidate is:
../src/fibers.cc:126:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:555:5: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:555:5: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:555:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:559:28: error: 'class Fiber' has no member named 'ReturnYielded'
../src/fibers.cc:559:49: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::Reset(const Arguments&)':
../src/fibers.cc:567:38: error: no match for call to '(Fiber) (v8::Local<v8::Object>)'
../src/fibers.cc:570:24: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc:570:24: note: suggested alternatives:
/home/pi/.node-gyp/6.7.0/include/node/v8.h:8532:18: note:   'v8::Undefined'
/home/pi/.node-gyp/6.7.0/include/node/v8.h:8532:18: note:   'v8::Undefined'
../src/fibers.cc:570:58: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:572:5: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:572:5: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:572:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:574:5: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:574:5: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:574:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:582:4: error: 'Handle' was not declared in this scope
../src/fibers.cc:582:16: error: expected primary-expression before '>' token
../src/fibers.cc:582:18: error: 'val' was not declared in this scope
../src/fibers.cc:582:24: error: 'Deref' is not a member of 'uni'
../src/fibers.cc:585:24: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:585:68: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:587:33: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In member function 'void Fiber::UnwindStack()':
../src/fibers.cc:604:4: error: 'Handle' was not declared in this scope
../src/fibers.cc:604:16: error: expected primary-expression before '>' token
../src/fibers.cc:604:54: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:605:64: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Persistent<v8::Value>&)'
../src/fibers.cc:605:64: note: candidate is:
../src/fibers.cc:126:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:606:49: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Persistent<v8::Value>&)'
../src/fibers.cc:606:49: note: candidate is:
../src/fibers.cc:126:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:619:41: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc:619:41: note: suggested alternatives:
/home/pi/.node-gyp/6.7.0/include/node/v8.h:8532:18: note:   'v8::Undefined'
/home/pi/.node-gyp/6.7.0/include/node/v8.h:8532:18: note:   'v8::Undefined'
../src/fibers.cc: In static member function 'static void Fiber::RunFiber(void**)':
../src/fibers.cc:681:5: error: 'Handle' was not declared in this scope
../src/fibers.cc:681:19: error: expected primary-expression before '>' token
../src/fibers.cc:366:23: error: invalid use of member 'Fiber::v8_context' in static member function
../src/fibers.cc:681:21: error: from this location
../src/fibers.cc:681:34: error: 'Deref' is not a member of 'uni'
../src/fibers.cc:366:23: error: invalid use of member 'Fiber::v8_context' in static member function
../src/fibers.cc:682:5: error: from this location
../src/fibers.cc:686:21: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:688:17: error: expected primary-expression before '>' token
../src/fibers.cc:368:21: error: invalid use of member 'Fiber::yielded' in static member function
../src/fibers.cc:688:19: error: from this location
../src/fibers.cc:690:18: error: expected primary-expression before '>' token
../src/fibers.cc:690:20: error: 'argv' was not declared in this scope
../src/fibers.cc:368:21: error: invalid use of member 'Fiber::yielded' in static member function
../src/fibers.cc:691:6: error: from this location
../src/fibers.cc:691:16: error: 'Deref' is not a member of 'uni'
../src/fibers.cc:366:23: error: invalid use of member 'Fiber::v8_context' in static member function
../src/fibers.cc:691:56: error: from this location
../src/fibers.cc:368:21: error: invalid use of member 'Fiber::yielded' in static member function
../src/fibers.cc:693:6: error: from this location
../src/fibers.cc:693:16: error: 'Deref' is not a member of 'uni'
../src/fibers.cc:366:23: error: invalid use of member 'Fiber::v8_context' in static member function
../src/fibers.cc:693:56: error: from this location
../src/fibers.cc:697:66: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Local<v8::Value>)'
../src/fibers.cc:697:66: note: candidate is:
../src/fibers.cc:126:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:699:45: error: 'Deref' is not a member of 'uni'
../src/fibers.cc:699:98: error: 'Deref' is not a member of 'uni'
../src/fibers.cc:701:67: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Local<v8::Value>)'
../src/fibers.cc:701:67: note: candidate is:
../src/fibers.cc:126:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:368:21: error: invalid use of member 'Fiber::yielded' in static member function
../src/fibers.cc:704:45: error: from this location
../src/fibers.cc:366:23: error: invalid use of member 'Fiber::v8_context' in static member function
../src/fibers.cc:719:5: error: from this location
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::Yield_(const Arguments&)':
../src/fibers.cc:734:5: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:734:5: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:734:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:740:24: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:740:58: error: 'Deref' is not a member of 'uni'
../src/fibers.cc:740:112: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:742:74: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Local<v8::Primitive>)'
../src/fibers.cc:742:74: note: candidate is:
../src/fibers.cc:126:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:744:51: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Local<v8::Value>)'
../src/fibers.cc:744:51: note: candidate is:
../src/fibers.cc:126:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:746:5: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:746:5: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:746:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:769:28: error: 'class Fiber' has no member named 'ReturnYielded'
../src/fibers.cc:769:49: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::GetStarted(v8::Local<v8::String>, const GetterCallbackInfo&)':
../src/fibers.cc:777:24: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc:777:24: note: suggested alternatives:
/home/pi/.node-gyp/6.7.0/include/node/v8.h:324:27: note:   'v8::Undefined'
/home/pi/.node-gyp/6.7.0/include/node/v8.h:324:27: note:   'v8::Undefined'
../src/fibers.cc:777:67: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:779:36: error: no match for call to '(Fiber) (v8::Local<v8::Object>)'
../src/fibers.cc:780:23: error: 'NewBoolean' is not a member of 'uni'
../src/fibers.cc:780:72: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::GetCurrent(v8::Local<v8::String>, const GetterCallbackInfo&)':
../src/fibers.cc:787:24: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc:787:24: note: suggested alternatives:
/home/pi/.node-gyp/6.7.0/include/node/v8.h:324:27: note:   'v8::Undefined'
/home/pi/.node-gyp/6.7.0/include/node/v8.h:324:27: note:   'v8::Undefined'
../src/fibers.cc:787:67: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::GetPoolSize(v8::Local<v8::String>, const GetterCallbackInfo&)':
../src/fibers.cc:795:23: error: 'NewNumber' is not a member of 'uni'
../src/fibers.cc:795:88: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function 'static void Fiber::SetPoolSize(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&)':
../src/fibers.cc:799:27: error: 'ToNumber' is not a member of 'uni'
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::GetFibersCreated(v8::Local<v8::String>, const GetterCallbackInfo&)':
../src/fibers.cc:806:23: error: 'NewNumber' is not a member of 'uni'
../src/fibers.cc:806:99: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function 'static void Fiber::Init(int)':
../src/fibers.cc:824:4: error: 'Handle' was not declared in this scope
../src/fibers.cc:824:27: error: expected primary-expression before '>' token
../src/fibers.cc:824:36: error: 'NewFunctionTemplate' is not a member of 'uni'
../src/fibers.cc:825:41: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::FunctionTemplate>&, v8::Persistent<v8::FunctionTemplate>&)'
../src/fibers.cc:825:41: note: candidate is:
../src/fibers.cc:126:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:826:8: error: base operand of '->' has non-pointer type 'v8::Persistent<v8::FunctionTemplate>'
../src/fibers.cc:826:23: error: 'NewLatin1Symbol' is not a member of 'uni'
../src/fibers.cc:830:20: error: expected primary-expression before '>' token
../src/fibers.cc:830:22: error: 'sig' was not declared in this scope
../src/fibers.cc:830:28: error: 'NewSignature' is not a member of 'uni'
../src/fibers.cc:831:8: error: base operand of '->' has non-pointer type 'v8::Persistent<v8::FunctionTemplate>'
../src/fibers.cc:834:25: error: expected primary-expression before '>' token
../src/fibers.cc:834:27: error: 'proto' was not declared in this scope
../src/fibers.cc:834:39: error: base operand of '->' has non-pointer type 'v8::Persistent<v8::FunctionTemplate>'
../src/fibers.cc:835:15: error: 'NewLatin1Symbol' is not a member of 'uni'
../src/fibers.cc:836:5: error: 'NewFunctionTemplate' is not a member of 'uni'
../src/fibers.cc:836:58: error: expected primary-expression before '>' token
../src/fibers.cc:836:60: error: expected primary-expression before ')' token
../src/fibers.cc:837:15: error: 'NewLatin1Symbol' is not a member of 'uni'
../src/fibers.cc:838:5: error: 'NewFunctionTemplate' is not a member of 'uni'
../src/fibers.cc:838:56: error: expected primary-expression before '>' token
../src/fibers.cc:838:58: error: expected primary-expression before ')' token
../src/fibers.cc:839:15: error: 'NewLatin1Symbol' is not a member of 'uni'
../src/fibers.cc:840:5: error: 'NewFunctionTemplate' is not a member of 'uni'
../src/fibers.cc:840:62: error: expected primary-expression before '>' token
../src/fibers.cc:840:64: error: expected primary-expression before ')' token
../src/fibers.cc:841:23: error: 'NewLatin1Symbol' is not a member of 'uni'
../src/fibers.cc:844:19: error: expected primary-expression before '>' token
../src/fibers.cc:844:21: error: 'yield' was not declared in this scope
../src/fibers.cc:844:29: error: 'NewFunctionTemplate' is not a member of 'uni'
../src/fibers.cc:845:17: error: expected primary-expression before '>' token
../src/fibers.cc:845:19: error: 'sym_yield' was not declared in this scope
../src/fibers.cc:845:31: error: 'NewLatin1Symbol' is not a member of 'uni'
../src/fibers.cc:846:4: error: 'target' was not declared in this scope
../src/fibers.cc:849:19: error: expected primary-expression before '>' token
../src/fibers.cc:849:21: error: 'fn' was not declared in this scope
../src/fibers.cc:849:30: error: base operand of '->' has non-pointer type 'v8::Persistent<v8::FunctionTemplate>'
../src/fibers.cc:851:34: error: 'NewLatin1Symbol' is not a member of 'uni'
../src/fibers.cc:852:34: error: 'NewLatin1Symbol' is not a member of 'uni'
../src/fibers.cc:853:34: error: 'NewLatin1Symbol' is not a member of 'uni'
../src/fibers.cc:856:16: error: 'NewLatin1Symbol' is not a member of 'uni'
../src/fibers.cc: At global scope:
../src/fibers.cc:872:11: error: variable or field 'init' declared void
../src/fibers.cc:872:11: error: 'Handle' was not declared in this scope
../src/fibers.cc:872:24: error: expected primary-expression before '>' token
../src/fibers.cc:872:26: error: 'target' was not declared in this scope
fibers.target.mk:101: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/homebridge-lightwaverf/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.1.19-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-lightwaverf/node_modules/fibers
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: 1: nodejs: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@2.0.0 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-10-11T21_22_28_187Z-debug.log
