### ISSUE TITLE
Keep getting no response and no connection to lightwaverf link

### ISSUE THREAD

**Issue by alialki** [rooi/homebridge-lightwaverf#35]
hi 
I have setup my homebridge on a rPi 3 and everything seems to be setup correctly as i am getting sending messages log on the homebridge but on home app i keep getting no response error and the homebridge seems not to be connected to lightwaverf link. I have tried the code in the terminal but nothing happens on the rPi or the lightwaverf link. Could anyone help me ?

**Comment by rooi** [comment]
Hi,

Did you allow connection to the ICS-1000 or Lightwave link?
Try to issue a command using homekit and click yes on the device or use the following:

For Mac OSX, (nix, or rPi - can anyone verify?) in a Terminal Window, run echo -ne '100,!F*p' | nc -u 192.168.yyy.xxx 9760 be sure to select the right IP address. Ctrl+C to close the Echo window For Windows PC

Download PacketSender - https://packetsender.com/ Send 100,!F*p. to the Lightwave Link on port 9760 When the Lightwave Link starts flashing, press the Link button

Does this help out?

If not please specify some more details. Are you using the old lightwaverf or KAKU link devices with four digit pins? Perhaps you can include a log (note: the password may be displayed, so remove it).

**Comment by alialki** [comment]
hi there 
I tried the echo command on terminal in rpi and it suddenly started to work. which was odd i did try the command 100 times but nothing happened. Anyway the important thing is that it works 

thanks a lot for the help
