### ISSUE TITLE
How to obtain a PIN?

### ISSUE THREAD

**Issue by jamesgrant1981** [rooi/homebridge-lightwaverf#37]
Hello... I'm brand new to Lightwave... and got the hub working fine, and have a nice homebridge setup working with other switches and bits and pieces.

I only registered for an account on the LightwaveRF website today, but can't seem to be able to find my PIN or how to generate one anywhere? I simply use my email address to log in. Everything is happily configured in manager.lightwaverf.com there, so I know the hub is happy... Oh by the way it's a first gen hub, does that make any difference? I used the first part of the config.json:

"platforms": [
       {
         "platform": "LightWaveRF",
         "name": "LightWaveRF",
         "ip_address": "192.168.1.123",
         "manager_host": "lightwaverfhost.co.uk",
         "email": "name@host.com",
         "pin": "1234",
         "timeout": 1000
       }   
   ]

Obviously edited it with the information I knew, but I don't know where to locate a PIN? Also, the email... thats my username? Apologies, but reading some of the messages etc on here some people seemed to be using their MAC address of the hub instead?

Apologies if this is a really silly question - I cant seem to work it out at the moment lol :(

**Comment by rooi** [comment]
Hi James,

The lin only works for the old lightave link from before 2016. Do you have an old or new device? Please check the readme for tips to configure homebridge-lightwaverf for your device
