### ISSUE TITLE
Link plus | feature request

### ISSUE THREAD

**Issue by charliebird** [rooi/homebridge-lightwaverf#39]
Hi,
Would it possible to update the plugin to work with the Link Plus?
The Link Plus supports the older Connect series devices (as well as the new Smart Series ones)

Thanks

**Comment by rooi** [comment]
Hi,

It shouldn’t be too difficult to create a plugin that supports the link plus. It seems that no official api has been release, but there some work done in backwards engineering the cloud api: https://github.com/washcroft/LightwaveRF-LinkPlus
Unfortunately no local api, yet, so it relies on a stable internet connection.

That being said, I don’t think it’s wise to add the new link plus to this plugin. The api is very different and it would be easier to write a new homebridge plugin. 

I did not upgrade to the link plus myself and I’m not sure if I will, so it will be different for me to write such a plugin. The link plus seems interesting for the two way communication part, but this only works for new sockets and switches and there are some other manufacturers that offer similar functionality as well.

Cheers,

Roy

**Comment by charliebird** [comment]
Hi Roy,
Thanks for the reply.
Without an API it's not something I feel I could do.
In the meantime I found a workaround using IFTTT and the homebridge IFTTT plugin 

Thanks,
Charlie

**Comment by adavison007** [comment]
> Hi Roy,
> Thanks for the reply.
> Without an API it's not something I feel I could do.
> In the meantime I found a workaround using IFTTT and the homebridge IFTTT plugin
> 
> Thanks,
> Charlie

@charliebird there is a full Gen 2 Link Plus API now available and also API key from the app...

**Comment by rooi** [comment]
@adavison007 Thanks, I did not know that they published an API. I looked it up to determine if I would need/want to upgrade, but it seems that the API relies on an internet connection instead of using the local network as with the ics-1000. I will, therefore, not upgrade myself, but perhaps @charliebird or someone else can implement it.

**Comment by omarassil** [comment]
I installed the plugin but it doesn't seem to wrk with my Link Plus. Any plans to update the plugin by anyone?
