### ISSUE TITLE
HOOBS Install

### ISSUE THREAD

**Issue by AKWillows** [rooi/homebridge-lightwaverf#40]
Hi

I have been using this plug in for some time on an instance of Homebridge which I set up myself. However, my instance is, I think, pretty non-standard as some of the files appear to be in unusual places! So, I thought I would start again using HOOBS (Hoobs.org).

However, I am unable to install this plug in (which is vital for me) using their interface as I get an error. HOOBS support tell me that it is because the plug in is installing as root user rather than sudo mode. Does this sound correct to you and is there anything that can be done to sort it? Appreciate any help you can give!

**Comment by AKWillows** [comment]
<img width="789" alt="Screenshot 2019-08-28 at 14 32 22" src="https://user-images.githubusercontent.com/31076973/63862799-16c05100-c9a5-11e9-80ba-7b8f21e666e5.png">

**Comment by RugNum11** [comment]
I have the same issue using Hoobs - any pointers please?

![image](https://user-images.githubusercontent.com/54944319/64344696-e2711400-cfe6-11e9-8e92-29a9cb644096.png)

**Comment by rooi** [comment]
Hi,

I've just changed the dependency from git to https. Could you please try again using the latest GitHub or npm version and see if this solves it?

Thanks

**Comment by AKWillows** [comment]
Thank you. I was able to previously install it using some advice from HomeManager support using the Terminal of HOOBS as follows:

sudo apt install git
sudo -s
sudo npm i homebridge-lightwaverf -g --unsafe-perm

So that provided me a workaround - so I'm afraid I won't be able to test the new install effectively. Maybe @RugNum11 will be able to. What will happen if I update to the new version?

**Comment by rooi** [comment]
The install git command you mention indicates that my change should work as well. 

No difference, the dependency on git is now removed in the plugin, which is probably cleaner.

When you update you’ll to the new version, you should not notice anything new
