### ISSUE TITLE
How to add electric heating thermostats?

### ISSUE THREAD

**Issue by astirling01** [rooi/homebridge-lightwaverf#50]
I have 6 electric switches which have built in thermostats controlling my heating but can’t see a category to add them to the configuration file

**Comment by rooi** [comment]
Hi @astirling01 ,

Thermostats are not supported by this plugin, unfortunately. I do not expect to add them, since I don’t have them myself and am slowly transitioning to another lighting system.

Perhaps someone else can try to develop it and send a pull request to allow me to include it.

**Comment by astirling01** [comment]
Ah ok. Thanks for the response. I think they're on the road to obsolescence so thought a Homebridge plug in might be the best bet to extend their lifespan. There is a home assistant plug-in which supports them so might look at that.

**Comment by rooi** [comment]
That was my idea when creating this plugin but with more and more devices added the lacking two way communication get more annoying.
Home assistant would be a good workaround! I believe there is also a home assistant plugin that exposes accessories to homekit so you can have both
