### ISSUE TITLE
Unable to get link to ask to register

### ISSUE THREAD

**Issue by lmallender** [rooi/homebridge-lightwaverf#51]
Hi, apologies in advance, I am very very new to this, I have HOOBS (only installed today) and I am trying to get my Gen1 Lightwaverf gear into Homekit. I have installed the plugin and followed the instructions and all seemed to be great. I do have a very old lightwave link so I used the instructions relevant. All of my devices have appeared in home kit and are correct. However, I can't control them. When I send a command, homebridge is not registered on the link - and the link doesn't come up with a message asking me to register it. I have only tried to send a command via homekit or the accessory in hoobs but neither way does the link ask me to register. I have tried clearing the registers out of the link but to no avail. Any help would be very well received. I have also double-checked the IP address of the link as in the configuration and it is correct. 
![image](https://user-images.githubusercontent.com/96683850/147406177-5c00b4d9-a709-4522-9000-c89a9dd7a138.png)

**Comment by rooi** [comment]
Hi,

There may be settings on your network that could block the device from communicating, I suggest to try to exclude these first. Can you verify that the device can reach each other? Perhaps by opening a terminal in hoobs (I’m not familiar with it specifically, but look for some way to open an ssh terminal), and sendind a ping command.

ping <fill in ip adress of the link>

Another thing you can try are these steps from the readme

How to Register your HomeBridge server on Lightwave Link:

For Mac OSX, (nix, or rPi - can anyone verify?) in a Terminal Window, run echo -ne '100,!F*p' | nc -u 192.168.yyy.xxx 9760 be sure to select the right IP address. Ctrl+C to close the Echo window For Windows PC

Download PacketSender - https://packetsender.com/ Send 100,!F*p. to the Lightwave Link on port 9760 When the Lightwave Link starts flashing, press the Link button

**Comment by lmallender** [comment]
Hi,

 

Thank you so much for your reply. I appreciate it is me being a bit thick but I am not the most technical in the world. I have done the following: -

 

Connected to HOOBS using ssh (I think using a program called putty?) and verified that I can ping the Lightwave link from there (IP address of the Lightwave link is 192.168.1.17)



 

I have tried to run the command  echo -ne '100,!F*p' | nc -u 192.168.1.17 9760   If I run this from the cmd window on my PC I get the following



 

If I run it from the terminal window in HOOBS I get 



 

I have downloaded packet sender and tried to send the code as suggested – again not sure if I have done it correctly – and I get the following

 



 

I have temporarily switched off my Anti-Virus and tried again – that didn’t help

 

I have also tried to open the port on my router (again unsure if this is correct or not)

 



 

I think you are right, it does appear to be a connection issue, but I don’t know how to fix it. If you have any ideas I would be grateful, if not, then thank you for your help anyway, I really do appreciate it and I hope you have a good festive break.

 

Kind Regards

 

Lee

**Comment by rooi** [comment]
Hi Lee,

sure no problem.
It seems that some images are missing from you last post. Could you please include these, or paste the text from them in here.

I would recommend against opening any posts on your router for now. These typically expose your devices to the internet and this should function on your local network. I’m no networking expert but this could introduces security risk unless you confident enough and know what you’re changing.

Roy

**Comment by lmallender** [comment]
Hi, I have printed the email to pdf with screenshots. Thanks for taking the time to try and help me. 

I am wondering if I should buy a new later version Gen1 lightwave link. 

[email with images.pdf](https://github.com/rooi/homebridge-lightwaverf/files/7780045/email.with.images.pdf)

**Comment by rooi** [comment]
thanks Lee, could you try to install Netcat on your hoobs device. Then the nc command should work

it should be something like: sudo apt install netcat

https://linuxtect.com/netcat-nc-command-tutorial/

**Comment by lmallender** [comment]
You my friend are an absolute genius, I can’t thank you enough. I’m fine at following instructions but am not massively technical.

Thank you so very much, I am so grateful. Enjoy the rest of the holidays.

I’m going to try to learn about random delays now, something that’s missing in the Lightwave v2 which stopped me upgrading. A big learning curve but thanks to you I have something to spur me on. Thanks again.

Lee

Kind Regards

Lee
________________________________

**Comment by rooi** [comment]
Great, you've got it working right?
Enjoy and all the best for 2022!

**Comment by lmallender** [comment]
Yes, it’s working, the same to you too

Thank you



Kind Regards

Lee
________________________________
