### ISSUE TITLE
All lights are connected and show in my devices but won't turn on or off

### ISSUE THREAD

**Issue by gizbod** [rooi/homebridge-lightwaverf#6]
I have managed to get my lightwaverf linked to homebridge and when i run homebridge it connects all the lights and they show up in my devices on the app i use. when i command them to turn on through siri, siri says that the light has been tuned on. but nothing happens.
any ideas?
thanks

**Comment by gizbod** [comment]
I also have no control of the lights in the app i use for home kit which is called home

**Comment by rooi** [comment]
Hi, you probably have the new lightwaverf link which is not supported yet. Hopefully soon

**Comment by gizbod** [comment]
I do have the new link. That explains it. Thanks.
