### ISSUE TITLE
Accessory rather than service?

### ISSUE THREAD

**Issue by spartan1017** [rooi/homebridge-lightwaverf#9]
Trying for the first time with v0.0.7 and the older LWRF hub config.

Each device registered appears as an accessory, similar to the homebridge accessory rather than as independant switches/services.

Happy to provide iOS screenshots if that helps, not sure how else I can support debugging.

**Comment by rooi** [comment]
Hi @spartan1017,

You're right each light is registered as an individual accessory. I've made it such I think the lightwaverf should function. Why do you think it should be different?
